### ISSUE TITLE
Parent industry id dropdown list is blank in industry setup.

### ISSUE THREAD

**Issue by mixerp3** [mixerp/mixerp#267] opened 2015-06-03 10:17 UTC
Parent industry id is blank.
![industry](https://cloud.githubusercontent.com/assets/10184034/7957810/e09e44e2-0a09-11e5-855a-bb994f4acfe6.png)

**Comment by UlyssesAlves** [comment] 2015-06-03 11:15
I think it's because you are creating the first industry, and so there is no other industry to be selected as a parent industry, since there is no industry registered yet.

If this is the case, maybe the right thing to do should be not showing the Parent Industry Id field if there is no other industry in the database yet. After there is at least one industry saved in the database, then the Parent Industry Id should be shown to let users select the parent industry of the new industry being created.

**Comment by mixerp** [comment] 2015-06-03 15:31
@UlyssesAlves, I think the issue is correct because the properties "DisplayFields" and "DisplayViews" seem missing. :)

**Comment by mixerp** [comment] 2015-06-03 15:35
Please feel free to close this issue if the commit 291c280 solves it. :+1:

**Closed** 2015-06-05 07:33 UTC
Labels: bug, database
